# ~/.config/starship.toml
# '$schema' = 'https://starship.rs/config-schema.json'

add_newline = true
palette = 'catppuccin'


format = '''
[┌](bold surface1)[ $directory ](bg:peach)[](fg:peach bg:surface0)[$git_branch$git_commit](bold fg:blue bg:surface0)[](fg:surface0 bg:base) $fill [[](fg:surface0 bg:base)$conda](bold fg:yellow bg:surface0)[[](fg:rosewater bg:surface0) $time ](bold bg:rosewater)[┐](bold surface1)
[└](bold surface1) $username $character
'''

right_format = '''
$status $cmd_duration [┘](bold surface1)
'''


[fill]
symbol = '─'
style = 'bold surface1'

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
format = '[$read_only]($read_only_style)[$path]($style)'
truncation_length = 3
truncation_symbol = '…/'
read_only = '[] '
read_only_style = 'bold fg:base bg:peach'
style = 'bold fg:base bg:peach'

[username]
show_always = true
format = '[$user]($style)'
style_user = 'bold fg:mauve'
style_root = 'bold fg:peach'

[time]
format = '[$time]($style)'
use_12hr = true
time_format = '%I:%M %p'
disabled = false
style = 'bold fg:base bg:rosewater'

[cmd_duration]
format = '[$duration]($style)'
style = 'bold fg:blue'
min_time = 0

[status]
symbol = '(fg:red)'
not_found_symbol = '[](fg:red)'
#not_found_symbol = '[](fg:red)'
#success_symbol = '[](fg:green)'
success_symbol = '[](fg:green)'
format = '$symbol'
map_symbol = true
disabled = false

[git_branch]
symbol = ''
format = ' $symbol $branch(:$remote_branch)'

[git_commit] 
format = '  $hash '
tag_disabled = true
only_detached = false

[git_state]

[git_metrics]
disabled = false

[conda]
symbol = ''
format = '$symbol $environment '

# Catppuccin Macchiato
[palettes.catppuccin]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
